Mission04_alexm99/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_alexm99.Models
{
    public class GradeCalculatorModel
    {
        //This will build the entire get/set for you
        [Range (0,100)]
        public string Assignments { get; set; }
        [Range(0, 100)]
        public string Group_Project { get; set; }
        [Range(0, 100)]
        public string Quizzes { get; set; }
        [Range(0, 100)]
        public string Midterm_Exam { get; set; }
        [Range(0, 100)]
        public string Final_Exam { get; set; }
        [Range(0, 100)]
        public string INTEX { get; set; }

    }
}

Mission04_alexm99/Controllers/SomethinController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_alexm99.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_alexm99.Controllers
{
    public class SomethinController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission04_alexm99/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="img/turtle-icon.png" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/mydefault.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Somethin" asp-action="Index">Home</a>
        <a asp-controller="Somethin" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
</body>
</html>

Mission04_alexm99/Views/Somethin/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Calculate your Grade!";

}

@model GradeCalculatorModel;

<h2>Calculate your Grade Below</h2>
<br />
<form method="post">
    <h3>Put your current percentage scored for each grade category</h3>
    <label for="txtAssignments">Assignments:</label>
    <input id="txtAssignments" asp-for="Assignments" />% <br />

    <label for="txtGroupProject">Group Project:</label>
    <input id="txtGroupProject" asp-for="Group_Project" />% <br />

    <label>Quizzes:</label>
    <input id="txtQuizzes" asp-for="Quizzes" />% <br />

    <label>Midterm Exam:</label>
    <input id="txtMidtermExam" asp-for="Midterm_Exam" />% <br />

    <label>Final Exam:</label>
    <input id="txtFinalExam" asp-for="Final_Exam" />% <br />

    <label>INTEX:</label>
    <input id="txtINTEX" asp-for="INTEX" />% <br />

    <input id="btnSend" type="submit" value="Submit Grades" />

    <br />
    <label>Final Grade Percentage: </label>
    <input id="finalPercentage" type="number" disabled />
    <label>Final Letter Grade: </label>
    <input id="letterGrade" type="text" disabled />
    <div asp-validation-summary="All"></div>

</form>
<script src="~/js/GradeCalculator.js"></script>

Mission04_alexm99/Views/Somethin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mexican Bobble Head Turtles";
}

<h1>My Preferred Name: Alex</h1>
<img id="picAlexSports" src="img/Alex_Sports.jpg" />
<p>
    This semeseter I'm very excited to tackle my fears of learning lots of new things!
    I know that there are a lot of different types of technologies to learn, but this semester
    I can't wait to truly feel like I have a grasp on programming, web dev and using data in various ways!
</p>

<h2>My Top 3 jobs post graduation:</h2>
<ul>
    <li>Salesforce Consultant/Administrator</li>
    <li>Junior Developer</li>
    <li>Stay at home Dad :)</li>
</ul>